### ISSUE TITLE
problems with package.json

### ISSUE THREAD

**Issue by shapeshifta78** [mbrevoort/docco-husky#18]
Hi there, 

my package.json looks like this

```
"docco_husky": {
    "output_dir": "jsdocs",                  
    "project_name": "Your Project name",
    "show_timestamp": true                    
}
```

and I always get this error:
docco: Recursively generating documentation for js
Error parsing package.json
[SyntaxError: Unexpected token :]

/usr/local/lib/node_modules/docco-husky/lib/docco.js:384
    return context.config = _.extend(defaults, pkg.docco_husky || {});
                                                  ^
TypeError: Cannot read property 'docco_husky' of undefined
    at /usr/local/lib/node_modules/docco-husky/lib/docco.js:384:51
    at /usr/local/lib/node_modules/docco-husky/lib/docco.js:402:5
    at /usr/local/lib/node_modules/docco-husky/lib/docco.js:371:14
    at ChildProcess.exithandler (child_process.js:280:7)
    at ChildProcess.emit (events.js:70:17)
    at maybeExit (child_process.js:362:16)
    at Socket.<anonymous> (child_process.js:459:7)
    at Socket.emit (events.js:67:17)
    at Array.0 (net.js:335:10)
    at EventEmitter._tickCallback (node.js:190:38)

Am I doing sth. wrong?

Otherwise a cool tool :)

**Comment by shapeshifta78** [comment]
Found the problem looking at your json-file ... Maybe the documentation is a bit misleading.
