### ISSUE TITLE
valid package.json breaks docco-husky

### ISSUE THREAD

**Issue by Morriz** [mbrevoort/docco-husky#22]
I use a valid package.json like this;

{
    "name"           : "bla",
    "version"        : "0.0.1",
    "description"    : "bla di bla",
    "keywords"       : [],
    "authors"        : [
        {
            "name" : "bla",
            "email": "bla@bla.om"
        },
        {
            "name" : "more bla",
            "email": "morebla@bla.om"
        }
    ],
    "main"           : "",
    "devDependencies": {
        "requirejs"   : "2.0.5",
        "jasmine-node": "1.0.26"
    },
    "docco_husky"    : {
        "output_dir"    : "doc/gen",
        "project_name"  : "blabla",
        "show_timestamp": true
    }
}

But get an error like this:

/usr/local/lib/node_modules/docco-husky/node_modules/jade/lib/runtime.js:117
  throw err;
        ^
TypeError: /usr/local/lib/node_modules/docco-husky/lib/../resources/readme.jade:63
    61|                 h3 Dependencies 
    62|                 ul

> 63|                   each dep, key in package_json.dependencies
>     64|                     li 
>     65|                       b #{key} 
>     66|                       span #{dep}

Cannot read property 'length' of undefined
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/docco-husky/node_modules/jade/lib/jade.js:161:8))
    at eval (eval at <anonymous> (/usr/local/lib/node_modules/docco-husky/node_modules/jade/lib/jade.js:161:8))
    at exports.compile (/usr/local/lib/node_modules/docco-husky/node_modules/jade/lib/jade.js:166:12)
    at generate_readme (/usr/local/lib/node_modules/docco-husky/lib/docco.js:144:14)
    at cloc (/usr/local/lib/node_modules/docco-husky/lib/docco.js:216:14)
    at ChildProcess.exithandler (child_process.js:534:7)
    at ChildProcess.EventEmitter.emit (events.js:91:17)
    at maybeClose (child_process.js:634:16)
    at Process._handle.onexit (child_process.js:676:5)

**Comment by Morriz** [comment]
I found that it breaks on the "name" section. No matter what string you put in there, docco-husky breaks....

**Comment by fiveisprime** [comment]
I think this is because you don't have a `dependencies` object in your package. Just add `"dependencies" : {},` somewhere in there and try it again.

**Comment by Morriz** [comment]
I was just about to write you, but you're too fast ;)

**Comment by fiveisprime** [comment]
Glad you got it working. :D
